Task2
alivkas/speed-printing-master pull request #27
Opened 2024-11-30 20:43 UTC by alivkas

2024-12-01 16:42 UTC, YaEtoTui commented on src/test/java/org/example/database/dao/UserDaoTest.java
> +        assertThrows(IllegalArgumentException.class, () -> {
Ребят, уже не смешно валится на таких ошибках. Все таки вам это рассказывали. Поправить в данном классе аналогичные ошибки

2024-12-01 16:43 UTC, YaEtoTui commented on src/test/java/org/example/database/dao/UserDaoTest.java
> +package org.example.service;
Думаю вы поняли почему я на это обратил внимание

2024-12-01 16:54 UTC, YaEtoTui commented on src/main/java/org/example/service/UserAuth.java
> +    private String username;
Смотрю, и не понимаю для чего это поле? Может вы мне подскажете

2024-12-01 16:55 UTC, YaEtoTui commented on src/main/java/org/example/service/UserAuth.java
> +     * Проверить наличие пользователя в базе данных из текущей сессии
Если что проверка это не loginUser хотя бы там должно быть слово check...

2024-12-01 16:56 UTC, YaEtoTui commented on src/main/java/org/example/service/UserTraining.java
> +    private boolean addNewTrainingSession(String username,
хм. А нужно ли возвращать значение?

2024-12-01 16:56 UTC, YaEtoTui commented on src/main/java/org/example/service/UserTraining.java
> +    private boolean addNewTrainingSession(String username,
У вас как бы оно используется) И там не важно что метод возвращает

2024-12-01 17:04 UTC, YaEtoTui commented on src/test/java/org/example/service/UserAuthTest.java
> +public class UserAuthTest {
javaDoc не написан

2024-12-01 17:06 UTC, YaEtoTui commented
Замечания есть

2024-12-02 08:02 UTC, alivkas commented on src/test/java/org/example/database/dao/UserDaoTest.java
> +        assertThrows(IllegalArgumentException.class, () -> {
исправили все такие места

2024-12-02 08:03 UTC, alivkas commented on src/test/java/org/example/database/dao/UserDaoTest.java
> +package org.example.service;
изменили на правильный пакет

2024-12-02 08:03 UTC, alivkas commented on src/main/java/org/example/service/UserAuth.java
> +    private String username;
оставалось после старой реализации. Поле удалили

2024-12-02 08:04 UTC, alivkas commented on src/main/java/org/example/service/UserAuth.java
> +     * Проверить наличие пользователя в базе данных из текущей сессии
Изменили javadoc

2024-12-02 08:05 UTC, alivkas commented on src/main/java/org/example/service/UserTraining.java
> +    private boolean addNewTrainingSession(String username,
также осталось от старой реализации. Изменили на void

2024-12-02 08:05 UTC, alivkas commented on src/test/java/org/example/service/UserAuthTest.java
> +public class UserAuthTest {
написали

2024-12-02 15:17 UTC, YaEtoTui commented
Замечания мои исправлены. 2-ое задание принято

2024-12-05 20:57 UTC, vpyzhyanov requested changes
очень много ошибок и тёмной стороны

И почините уже сборку, наконец. Нехорошо, что она сама себя вызывает в бесконечном цикле.

2024-12-05 20:57 UTC, vpyzhyanov commented on pom.xml
> +            <artifactId>hibernate-core</artifactId>
походу вы не ищете лёгких путей. Могли выбрать ORM попроще

2024-12-05 20:57 UTC, vpyzhyanov commented on src/main/java/org/example/animation/Animation.java
> +    private final LogsWriterUtils logsWriter = new LogsWriterUtils(LogsFile.FILE_NAME);
похоже вы любители изобрести велосипед. Такие вещи уже давным давно придуманы и сделаны. Посмотрите на sfj4j и log4j

2024-12-05 20:57 UTC, vpyzhyanov commented on src/main/java/org/example/animation/Animation.java
> +                logsWriter.writeStackTraceToFile(e);
не надо ничего логгировать, если вы выбрасываете исключение

2024-12-05 20:57 UTC, vpyzhyanov commented on src/main/java/org/example/commons/Time.java
> +    public static final int MILLISECONDS = 60000;
Название ни о чём не говорит. С таким же успехом можете переименовать ваш класс в `Class`, а весь проект в `Project`.

Это поле должно иметь JavaDoc и называться в соответствии с его **смыслом**, а не единицы измерения. Например, `MILLISECONDS_IN_MINUTE`

2024-12-05 20:57 UTC, vpyzhyanov commented on src/main/java/org/example/database/DatabaseManager.java
> +        sessionManager.startSession(configuration);
Тёмная сторона построенная на тёмной стороне.

С названиями вообще беда.

1. Метод называется startDb, но вызывает метод startSession
2. Метод называется startDb, но чтобы запустить БД, надо её создать. Если вы её создаёте, то полностью теряете весь смысл БД. Тогда зачем она вам?
3. Метод startSession, судя по названию, должен создавать сессию, но он никакую сессию не создаёт и вообще он void, что очень странно.

2024-12-05 20:57 UTC, vpyzhyanov commented on src/main/java/org/example/database/SessionManager.java
> +        sessionFactory = configuration.buildSessionFactory();
Кругом ложь и обман. Нет тут никого запуска сессии. Есть только построение sessionFactory, больше ничего тут нет.

2024-12-05 20:57 UTC, vpyzhyanov commented on src/main/java/org/example/database/SessionManager.java
> +            logsWriter.writeStackTraceToFile(new IllegalStateException());
Это что такое? Создание пустого исключения просто ради стека? А смысл?

1. Нет человекочитаемого сообщения об ошибке
2. Этот стек вообще бесполезен
3. Дальше кидатеся ислкючение, поэтому логгирования тут быть вообще не должно. Оно будет там, где вы обрабатываете это исключение.

2024-12-05 20:57 UTC, vpyzhyanov commented on pom.xml
> +            <artifactId>h2</artifactId>
что интересно, вижу использование H2, но почему-то scope не test. Очень подозрительно.

2024-12-05 20:57 UTC, vpyzhyanov commented on src/main/resources/hibernate.cfg.xml
> +        <property name="hibernate.connection.url">jdbc:h2:file:./data/speedprintdb;DB_CLOSE_DELAY=-1</property>
а нет, всё норм. БД сохраняется в файл хотя бы.

2024-12-05 20:57 UTC, vpyzhyanov commented on src/main/java/org/example/database/dao/UserDao.java
> +            logsWriter.writeStackTraceToFile(new IllegalArgumentException());
убрать

2024-12-05 20:57 UTC, vpyzhyanov commented on src/main/java/org/example/database/entity/base/BaseEntity.java
> +    public Long id;
инкапсуляция - давай до свидания!

2024-12-05 20:57 UTC, vpyzhyanov commented on src/main/java/org/example/database/logger/HibernateLoggingConfigurator.java
> +    public void disableHibernateLogging() {
это делается через конфигурационный файл настройки логгирования. См. slf4j и log4j

2024-12-05 20:57 UTC, vpyzhyanov commented on src/main/java/org/example/processing/CommandHandler.java
> +    protected final UserAuth userAuth;
опять дыра в инкапсуляции

2024-12-05 20:57 UTC, vpyzhyanov commented on src/main/java/org/example/processing/CommandHandler.java
> +    protected String currentUsername = null;
и тут дыра

2024-12-05 20:57 UTC, vpyzhyanov commented on src/main/java/org/example/processing/CommandHandler.java
> +            Transaction transaction = session.beginTransaction();
после того, как я рассказал как надо работать с транзакциями, такие вещи делать уже недопустимо!

Ещё и коллективную безотстветственность ввели. Зачем вам тогда databaseManager?

2024-12-05 20:57 UTC, vpyzhyanov commented on src/main/java/org/example/processing/CommandHandler.java
> +                transaction.rollback();
катастрофически неправильная работа с транзакциями. Совершенно ненадёжная, учитесь гуглить хотя бы.

2024-12-05 20:57 UTC, vpyzhyanov commented on src/main/java/org/example/processing/CommandHandler.java
> +                trainingSettings.setTrainingTime(0);
это что такое? Мы же обсуждали это! Почему выводы не сделали?

Срочное удаляем, вместе со всем классом `TrainingSettings`!

2024-12-05 20:57 UTC, vpyzhyanov commented on src/main/java/org/example/processing/CommandHandler.java
> +            logsWriter.writeStackTraceToFile(e);
убираем

2024-12-05 20:57 UTC, vpyzhyanov commented on src/main/java/org/example/processing/CommandHandler.java
> +            throw new TransactionException("Ошибка транзакции");
потеряли исходное исключение

2024-12-05 20:57 UTC, vpyzhyanov commented on src/main/java/org/example/utils/processing/TimeProcessingUtils.java
> +        return minute * Time.MILLISECONDS;
Невероятно простой метод, который используется ровно в одном месте. В чём был смысл создавать, даже не метод, а целый класс под это? Смысла никакого нет.

Если прочитать JavaDoc, то там очень громкие слова `Обработка времени`, но никакой обработки я тут не вижу. Просто конвертация одной единицы измерения в другую.

2024-12-05 20:57 UTC, vpyzhyanov commented on src/test/java/org/example/database/dao/UserDaoTest.java
> +class UserDaoTest {
Очень интересно что может тестировать тест для класса который отвечает за работу с БД, **без БД**. Удивите меня)

2024-12-05 20:57 UTC, vpyzhyanov commented on src/test/java/org/example/database/dao/UserDaoTest.java
> +        expectedUser.setUsername(username);
а не удобнее было конструктор создать?

2024-12-05 20:57 UTC, vpyzhyanov commented on src/test/java/org/example/database/dao/UserDaoTest.java
> +        assertEquals(expectedUser.getUsername(), actualUser.getUsername());
тестирование моков у нас не приветствуется.

Похоже тема по Mockito прошла мимо(((

2024-12-05 20:57 UTC, vpyzhyanov commented on src/test/java/org/example/service/UserAuthTest.java
> +        Field userDaoField = UserAuth.class.getDeclaredField("userDao");
вот это поворот! Магия вне Хогвартса запрещена! Убираем этот хак и делаем по человечески через нормальный конструктор.

2024-12-05 20:57 UTC, vpyzhyanov commented on src/test/java/org/example/service/UserAuthTest.java
> +        verify(sessionMock).save(any(UserEntity.class));
ну точно тема Mockito прошла мимо. Я объяснял, что в этом случае нужно проверять объект на полное совпадение

Ну и сложностей бы с этим не было, если бы вспомнили что означает первая буква в слове ООП. Начинайте использовать объекты, а не примитивы.

2024-12-05 20:57 UTC, vpyzhyanov commented on src/test/java/org/example/service/UserTrainingTest.java
> +        verify(sessionMock).merge(any(UserEntity.class));
И тут то же самое. Во всех тестах одно и то же

2024-12-05 20:57 UTC, vpyzhyanov commented on src/main/java/org/example/service/UserAuth.java
> +                session.save(newUser);
очень интересно, по какому принципу вы решаете где должна быть транзакция, а где нет?

2024-12-05 20:57 UTC, vpyzhyanov commented on src/main/java/org/example/service/UserAuth.java
> +            throw new SessionException("Ошибка сохранения");
опять лишний лог, и потеряли исходную ошибку с её стеком

2024-12-05 20:57 UTC, vpyzhyanov commented on src/main/java/org/example/service/UserAuth.java
> +                session.getTransaction().commit();
для операции получения данных вы используете транзакцию, а для операции изменения, почему-то нет. Вы вообще знаете, что такое транзакция? Надо срочно загуглить.

А databaseManager видимо просто для красоты у вас в проекте.

2024-12-05 20:58 UTC, vpyzhyanov commented on pom.xml
> +            <artifactId>hibernate-core</artifactId>
Или вообще самое простое, что только есть, JDBC драйвер

2024-12-09 13:54 UTC, SolevarLive commented on src/main/java/org/example/processing/CommandHandler.java
> +    protected final UserAuth userAuth;
Поменяли на private

2024-12-09 13:54 UTC, SolevarLive commented on src/main/java/org/example/processing/CommandHandler.java
> +    protected String currentUsername = null;
Поменяли на private

2024-12-09 13:57 UTC, SolevarLive commented on src/test/java/org/example/database/dao/UserDaoTest.java
> +class UserDaoTest {
Поменял тесты на "Интеграционные тесты", теперь тестируется все с БД

2024-12-09 13:57 UTC, SolevarLive commented on src/test/java/org/example/database/dao/UserDaoTest.java
> +        expectedUser.setUsername(username);
Да, вы правы

2024-12-09 13:59 UTC, SolevarLive commented on src/test/java/org/example/database/dao/UserDaoTest.java
> +        assertEquals(expectedUser.getUsername(), actualUser.getUsername());
Исправил эти ошибки  полной заменой тестов

2024-12-09 13:59 UTC, SolevarLive commented on src/test/java/org/example/service/UserAuthTest.java
> +        Field userDaoField = UserAuth.class.getDeclaredField("userDao");
Убрал, заменил на "Интеграционные тесты"

2024-12-09 14:00 UTC, SolevarLive commented on src/test/java/org/example/service/UserAuthTest.java
> +        verify(sessionMock).save(any(UserEntity.class));
Исправил эти ошибки с полной заменой тестов

2024-12-09 14:01 UTC, SolevarLive commented on src/test/java/org/example/service/UserTrainingTest.java
> +        verify(sessionMock).merge(any(UserEntity.class));
исправил аналогично предыдущим тестам

2024-12-09 14:05 UTC, alivkas commented on src/main/java/org/example/animation/Animation.java
> +    private final LogsWriterUtils logsWriter = new LogsWriterUtils(LogsFile.FILE_NAME);
класс LogsWriterUtils удален, вместо него поставлен log4j

2024-12-09 14:06 UTC, alivkas commented on src/main/java/org/example/animation/Animation.java
> +                logsWriter.writeStackTraceToFile(e);
удалили логгирование

2024-12-09 14:06 UTC, alivkas commented on src/main/java/org/example/commons/Time.java
> +    public static final int MILLISECONDS = 60000;
название изменено, добавлены джава доки на все константы в commons

2024-12-09 14:11 UTC, alivkas commented on src/main/java/org/example/database/DatabaseManager.java
> +        sessionManager.startSession(configuration);
класс DatabaseManager удален, так как по сути он является избыточным и управление бд находится в SessionManager. Метод startSession переименован в buildSessionFactory, так как он строит фабрику сессий из конфигурации Hibernate.

2024-12-09 14:11 UTC, alivkas commented on src/main/java/org/example/database/SessionManager.java
> +        sessionFactory = configuration.buildSessionFactory();
метод переименован вместе с javadoc

2024-12-09 14:13 UTC, alivkas commented on src/main/java/org/example/database/SessionManager.java
> +            logsWriter.writeStackTraceToFile(new IllegalStateException());
убрали логгирование. Теперь условие просто выкидывает исключение с сообщением, а в handleCommand оно обрабатывается

2024-12-09 14:14 UTC, alivkas commented on src/main/java/org/example/database/dao/UserDao.java
> +            logsWriter.writeStackTraceToFile(new IllegalArgumentException());
убрали

2024-12-09 14:14 UTC, alivkas commented on src/main/java/org/example/database/entity/base/BaseEntity.java
> +    public Long id;
заменили на private

2024-12-09 14:15 UTC, alivkas commented on src/main/java/org/example/database/logger/HibernateLoggingConfigurator.java
> +    public void disableHibernateLogging() {
Ккласс HibernateLoggingConfigurator был удален, теперь скрытием логов Hibernate занимается log4j

2024-12-09 14:17 UTC, alivkas commented on src/main/java/org/example/processing/CommandHandler.java
> +            Transaction transaction = session.beginTransaction();
Теперь транзакции обрабатываются на самом верхнем уровне в handleCommand.

2024-12-09 14:17 UTC, alivkas commented on src/main/java/org/example/processing/CommandHandler.java
> +                transaction.rollback();
Теперь транзакции обрабатываются на самом верхнем уровне в handleCommand, rollback происходит после отлавливания общего исключения

2024-12-09 14:18 UTC, alivkas commented on src/main/java/org/example/processing/CommandHandler.java
> +                trainingSettings.setTrainingTime(0);
Класс TrainingSettings полностью удален. Теперь Время тренировки у каждого пользователя храниться в бд

2024-12-09 14:19 UTC, alivkas commented on src/main/java/org/example/processing/CommandHandler.java
> +            logsWriter.writeStackTraceToFile(e);
удалили

2024-12-09 14:19 UTC, alivkas commented on src/main/java/org/example/processing/CommandHandler.java
> +            throw new TransactionException("Ошибка транзакции");
теперь есть отлов всех исключений

2024-12-09 14:20 UTC, alivkas commented on src/main/java/org/example/utils/processing/TimeProcessingUtils.java
> +        return minute * Time.MILLISECONDS;
класс с методом удалены

2024-12-09 14:23 UTC, alivkas commented on src/main/java/org/example/service/UserAuth.java
> +                session.save(newUser);
теперь транзакция существует только на верхнем уровне. В методах, где происходят изменения с данными мы получаем только текущую сессию и работаем с ней, а транзакция обрабатывается в handleCommand

2024-12-09 14:24 UTC, alivkas commented on src/main/java/org/example/service/UserAuth.java
> +            throw new SessionException("Ошибка сохранения");
удалили лог

2024-12-09 14:28 UTC, alivkas commented on src/main/java/org/example/service/UserAuth.java
> +                session.getTransaction().commit();
теперь в методе login транзакции нет, так как в нем нет изменения, удаления или добавления данных. Этот метод только получает данные о пользователе и сравнивает их с введенными

2024-12-10 19:54 UTC, vpyzhyanov commented on src/main/java/org/example/database/SessionManager.java
>      public Session getSession() {
с этим методом связано огромное количество дублирования кода. Это все места, где вы открываете транзакции. Я показывал как это делать и даже в чат скидывал пример.

А самое страшное - это потеря контроля над закрытием сессии. Правило всегда такое: "Кто открыл ресурс, тот и должен его закрыть". Если вы выкидываете сессию наружу, то обеспечить это требования - невозможно. И обязательно кто-то забудет закрыть сессию, вот например:

![image](https://github.com/user-attachments/assets/127d2d03-0c87-48ce-b413-9f40c5a0ed9d)

И накакой обработки ошибок нет! Не так я учил

2024-12-10 19:54 UTC, vpyzhyanov commented on src/test/java/org/example/training/TrainingSessionTest.java
> +        session.getTransaction().commit();
Сессия не закрывается.

> И накакой обработки ошибок нет! Не так я учил

2024-12-10 19:54 UTC, vpyzhyanov commented on src/main/java/org/example/database/SessionManager.java
> +            logsWriter.writeStackTraceToFile(new IllegalStateException());
> Теперь условие просто выкидывает исключение с сообщением

никакого смысла в этом нет. sessionFactory не может быть null, т.к. при ошибке инициализации (метод buildSessionFactory) выкидывает исключение. И программа завершит свою работу

2024-12-10 19:59 UTC, vpyzhyanov commented on src/main/java/org/example/database/SessionManager.java
>              throw new IllegalStateException("SessionFactory не инициализирован");
дублирую:

> > Теперь условие просто выкидывает исключение с сообщением
> 
> никакого смысла в этом нет. sessionFactory не может быть null, т.к. при ошибке инициализации (метод buildSessionFactory) выкидывает исключение. И программа завершит свою работу

Убираем проверку

2024-12-10 19:59 UTC, vpyzhyanov commented on pom.xml
> +            <artifactId>h2</artifactId>
Тесты мусорят ненужными файлами

![image](https://github.com/user-attachments/assets/2bb82600-859e-4895-bdd3-6c4262067340)

Что это за имя такое "speedprintdb.trace.db"? Судя по содержимому это лог. Почему он имеет расширение `.db`? должен быть `.log`

2024-12-10 20:01 UTC, vpyzhyanov commented on pom.xml
> +            <artifactId>h2</artifactId>
чтобы тесты не мусорили, нужно поднимать БД в оперативной памяти. H2 создана именно для этого. Чтобы она так делала её нужно особым образом настроить, и для тестов должна быть отдельная конфигурация

2024-12-10 20:02 UTC, vpyzhyanov commented on pom.xml
> +            <artifactId>h2</artifactId>
Только я не понимаю почему вы в тестах используете БД? Вы же используете Mockito. Либо выкидывайте Mockito, либо убирайте БД из тестов! Лучше БД убирайте.

2024-12-10 20:08 UTC, vpyzhyanov commented
Убираем БД из следующих тестов:

![image](https://github.com/user-attachments/assets/d6a25050-175a-4164-89bf-0c6776709728)

Тест UserDaoTest вообще тестирует базу данных. Если вы ей не доверяете, то выкидывайте её вообще из проекта. Не надо использовать то, чему вы не доверяете.

Эти 2 вещи несовместимы друг с другом. Всё равно что шашлык со сгущёнкой

![image](https://github.com/user-attachments/assets/034d9f47-3166-4af1-a5ad-6ce5eb8d82f7)

2024-12-10 20:12 UTC, vpyzhyanov commented on src/main/java/org/example/database/SessionManager.java
> +            throw new HibernateException("Ошибка во время взаимодействия с базой данных " +
`HibernateException` использовать некорректно. У вас не Hibernate. Используйте другое, например RuntimeException

2024-12-10 20:12 UTC, vpyzhyanov commented on src/main/java/org/example/database/SessionManager.java
> +            throw new HibernateException("Ошибка при создании SessionFactory", e);
`HibernateException ` использовать некорректно. У вас не Hibernate. Используйте другое, например RuntimeException

2024-12-10 20:12 UTC, vpyzhyanov commented on src/main/resources/hibernate.cfg.xml
> +        <property name="hibernate.connection.url">jdbc:h2:file:./data/speedprintdb;DB_CLOSE_DELAY=-1</property>
оказалось не норм, т.к. из-за этого мусорят тесты. В самом приложении всё ок, но тесты требует лишних данных и файлов.

2024-12-10 20:14 UTC, vpyzhyanov commented on src/main/java/org/example/database/entity/base/BaseEntity.java
> +    public Long id;
И всё? Как так? Даже геттеров и сеттеров не добавите? Походу поле вообще не используется нигде. Оно вам не нужно?

Если вам не нужно, то как минимум нужно для БД. Хотя бы геттер добавьте для приличия.

2024-12-10 20:16 UTC, vpyzhyanov commented on src/main/java/org/example/processing/CommandHandler.java
> +            Transaction transaction = session.beginTransaction();
> Ещё и коллективную безотстветственность ввели. Зачем вам тогда databaseManager?

Не исправлено! Только теперь не databaseManager, а sessionManager

2024-12-10 20:29 UTC, vpyzhyanov commented on src/main/java/org/example/training/TrainingSession.java
> +        int durationMilliseconds = (int) userTraining.getUserTrainingTime(username, session);
добро пожаловать в коллективную безответственность и большое количество никому не нужных аргументов! Ну зачем было тащить сессию куда ни попадя?! Вот зачем тренировке подключение к БД? Совершенно незачем!

Для тренировки нужно время тренировки, а не сессия и не пользователь. Правильно было заранее запросить время тренировки и передать только его.

2024-12-10 20:29 UTC, vpyzhyanov commented on src/main/java/org/example/training/TrainingSession.java
> +                    logger.info("Ошибка при работе с роботом");
вы уж определитесь либо error, либо info. Но info никогда не используют для информации об ошибке!

2024-12-10 20:29 UTC, vpyzhyanov commented on src/main/java/org/example/training/TrainingSession.java
> +                    logger.error(e.getMessage(), e);
где человекочитаемое исключение?

2024-12-10 20:29 UTC, vpyzhyanov commented on src/main/java/org/example/processing/CommandHandler.java
> +            logger.error(e.getMessage(), e);
где человекочитаемое исключение?

2024-12-10 20:29 UTC, vpyzhyanov commented on src/test/java/org/example/database/dao/UserDaoTest.java
> +class UserDaoTest {
Всё-таки удивили((( Этот тест абсолютно ничего в вашем приложении не тестирует. Он тестирует только внешнюю БД, которую тестировать не надо. Если не доверяете ей, то убирайте её вообще из проекта.

Вы уж определитесь либо вы пишете модульные тесты, либо интеграционные. Смешивать оба подхода в **ОДНОМ И ТОМ ЖЕ ТЕСТЕ** не надо! (модульные тесты - отдельно, интеграционные - отдельно)

2024-12-10 20:32 UTC, vpyzhyanov commented on src/test/java/org/example/database/dao/UserDaoTest.java
> +            transaction.commit();
некорректная работа с транзакциями

2024-12-10 20:32 UTC, vpyzhyanov commented on src/test/java/org/example/processing/CommandHandlerTest.java
> +            transaction.commit();
некорректная работа с транзакциями

И в этом классе совершенно неуместная

2024-12-10 20:32 UTC, vpyzhyanov commented on src/test/java/org/example/service/UserAuthTest.java
> +            transaction.commit();
некорректная работа с транзакциями

И тоже неуместная

И так далее и тому подобное во всех остальных тестах

2024-12-10 20:32 UTC, vpyzhyanov commented on src/test/java/org/example/database/dao/UserDaoTest.java
> +        assertEquals(expectedUser.getUsername(), actualUser.getUsername());
Моков в этом тесте не стало, но и смысла не прибавилось. Точно такой же ничего не тестирующий тест

2024-12-10 20:36 UTC, vpyzhyanov commented on src/test/java/org/example/service/UserAuthTest.java
> +        Field userDaoField = UserAuth.class.getDeclaredField("userDao");
Зачем? Лучше бы научились моками пользоваться правильно, было бы намного полезнее

Если вы хотите использовать именно интеграционные тесты, то тогда делайте их полноценными. Не вижу у вас ни одного полноценного интеграционного теста. Одни хаки да моки.

2024-12-10 20:37 UTC, vpyzhyanov commented on src/test/java/org/example/service/UserAuthTest.java
> +        verify(sessionMock).save(any(UserEntity.class));
Не исправили! Вместо того, чтобы проработать и исправить эти ошибки, вы решили всё переделать и совершить другие ошибки

2024-12-10 20:39 UTC, vpyzhyanov commented on src/test/java/org/example/service/UserTrainingTest.java
> +        verify(sessionMock).merge(any(UserEntity.class));
Не исправили! Вместо того, чтобы проработать и исправить эти ошибки, вы решили всё переделать и совершить другие ошибки

2024-12-10 20:43 UTC, vpyzhyanov requested changes
Давайте уберём остатки тёмной стороны и наведём порядок с тестами.

Я "порчу" файл `hibernate.cfg.xml`, и у меня падают тесты. Этого происходить не должно. В этом случае тесты должны проходить успешно.

2024-12-10 20:43 UTC, vpyzhyanov commented on src/main/java/org/example/service/UserAuth.java
> +            logger.error(e.getMessage(), e);
где человекочитаемое сообщение? `getMessage()` и так будет в стеке

2024-12-12 20:59 UTC, alivkas commented on src/main/java/org/example/database/SessionManager.java
> +            logsWriter.writeStackTraceToFile(new IllegalStateException());
удалили условие

2024-12-12 21:00 UTC, SolevarLive commented on src/test/java/org/example/training/TrainingSessionTest.java
> +        session.getTransaction().commit();
Удалили, вернули тесты через Mockito

2024-12-12 21:00 UTC, alivkas commented on pom.xml
> +            <artifactId>h2</artifactId>
в тестах бд теперь замокированна

2024-12-12 21:01 UTC, alivkas commented on src/main/resources/hibernate.cfg.xml
> +        <property name="hibernate.connection.url">jdbc:h2:file:./data/speedprintdb;DB_CLOSE_DELAY=-1</property>
бд замокированна, теперь при тестах файлы не создаются

2024-12-12 21:01 UTC, alivkas commented on src/main/java/org/example/database/entity/base/BaseEntity.java
> +    public Long id;
добавили геттер и сеттер

2024-12-12 21:02 UTC, alivkas commented on src/main/java/org/example/processing/CommandHandler.java
> +            Transaction transaction = session.beginTransaction();
создали метод для транзакции внутри SessionManager и теперь он используется в handleCommand

2024-12-12 21:04 UTC, alivkas commented on src/main/java/org/example/database/SessionManager.java
>      public Session getSession() {
теперь места где используется сессия в тестах замокированна

2024-12-12 21:05 UTC, alivkas commented on src/main/java/org/example/database/SessionManager.java
>              throw new IllegalStateException("SessionFactory не инициализирован");
убрали проверку

2024-12-12 21:05 UTC, alivkas commented on src/main/java/org/example/database/SessionManager.java
> +            throw new HibernateException("Ошибка во время взаимодействия с базой данных " +
поменяли отлов и выброс исключения

2024-12-12 21:05 UTC, SolevarLive commented on src/main/java/org/example/training/TrainingSession.java
> +        int durationMilliseconds = (int) userTraining.getUserTrainingTime(username, session);
Мы убрали необходимость передавать объект сессии и имя пользователя в метод start(). Теперь метод принимает только время тренировки в миллисекундах

2024-12-12 21:05 UTC, alivkas commented on src/main/java/org/example/database/SessionManager.java
> +            throw new HibernateException("Ошибка при создании SessionFactory", e);
поменяли отлов и выброс исключения

2024-12-12 21:06 UTC, SolevarLive commented on src/test/java/org/example/database/dao/UserDaoTest.java
> +            transaction.commit();
Удалили

2024-12-12 21:06 UTC, alivkas commented on src/main/java/org/example/training/TrainingSession.java
> +        int durationMilliseconds = (int) userTraining.getUserTrainingTime(username, session);
теперь метод start принимает в себя время

2024-12-12 21:06 UTC, alivkas commented on src/main/java/org/example/training/TrainingSession.java
> +                    logger.error(e.getMessage(), e);
добавили сообщение

2024-12-12 21:06 UTC, alivkas commented on src/main/java/org/example/processing/CommandHandler.java
> +            logger.error(e.getMessage(), e);
добавили сообщение

2024-12-12 21:06 UTC, SolevarLive commented on src/test/java/org/example/processing/CommandHandlerTest.java
> +            transaction.commit();
Удалили из-за ненадобности

2024-12-12 21:06 UTC, alivkas commented on src/main/java/org/example/service/UserAuth.java
> +            logger.error(e.getMessage(), e);
добавили сообщение

2024-12-12 21:07 UTC, SolevarLive commented on src/test/java/org/example/service/UserAuthTest.java
> +            transaction.commit();
Удалили из-за ненадобности, так как больше не используется

2024-12-12 21:08 UTC, SolevarLive commented on src/test/java/org/example/service/UserTrainingTest.java
> +        verify(sessionMock).merge(any(UserEntity.class));
Вернули обратно Mockito, исправили предыдущие замечания

2024-12-12 21:09 UTC, SolevarLive commented on src/test/java/org/example/service/UserAuthTest.java
> +        verify(sessionMock).save(any(UserEntity.class));
Вернули обратно Mockito, исправили предыдущие замечания

2024-12-12 21:10 UTC, SolevarLive commented on src/test/java/org/example/database/dao/UserDaoTest.java
> +class UserDaoTest {
Удалили потому что мы доверяем базе данных

2024-12-12 21:12 UTC, SolevarLive commented on src/test/java/org/example/service/UserAuthTest.java
> +        Field userDaoField = UserAuth.class.getDeclaredField("userDao");
Отказались от интеграционных тестов, переписали все под Mockito

2024-12-13 19:43 UTC, vpyzhyanov approved these changes
К сожалению не всю тёмную сторону удалось победить. Но основные проблемы исправлены, как исправите последние замечания, можете мёрджить. Задача принята.

ООП: 4 балла
Git: 3 балла

2024-12-13 19:43 UTC, vpyzhyanov commented on src/test/java/org/example/service/UserAuthTest.java
> +        userAuth = new UserAuth(inputOutputMock, userDaoMock);
Написал в общий чат комментарий про `@BeforeEach`. Это как раз тот случай, когда он не уместен

2024-12-13 19:43 UTC, vpyzhyanov commented on src/test/java/org/example/service/UserAuthTest.java
> +        UserEntity expectedUser = new UserEntity();
самим объектом вы не пользуетесь. Незачем было его создавать

2024-12-13 19:43 UTC, vpyzhyanov commented on src/test/java/org/example/service/UserAuthTest.java
> +        assertEquals(expectedUser.getUsername(), savedUser.getUsername());
expectedUser тут не нужен, можно же сразу без посредников сравнить с нужным значением

2024-12-13 19:43 UTC, vpyzhyanov commented on src/test/java/org/example/service/UserAuthTest.java
> +        newUser.setTime(0
что-то с методом пошло не так

2024-12-13 19:43 UTC, vpyzhyanov commented on src/test/java/org/example/service/UserAuthTest.java
> +        verify(sessionMock, never()).save(newUser);
не так я учил делать проверки. Почитайте лекцию про Mockito ещё раз

2024-12-13 19:43 UTC, vpyzhyanov commented on src/test/java/org/example/service/UserTrainingTest.java
> +        userTraining = new UserTraining(inputOutputMock, userDaoMock);
то же самое про `@BeforeEach`

2024-12-13 19:43 UTC, vpyzhyanov commented on src/test/java/org/example/service/UserTrainingTest.java
> +        verify(sessionMock, never()).merge(userEntity);
не так я учил делать

2024-12-13 19:43 UTC, vpyzhyanov commented on src/test/java/org/example/training/TrainingSessionTest.java
> +        trainingSession = new TrainingSession(inputOutputMock);
везде такая проблема с `@BeforeEach`

2024-12-13 19:43 UTC, vpyzhyanov commented on src/test/java/org/example/training/TrainingSessionTest.java
> +                + 100);
легко сразу посчитать

2024-12-13 19:43 UTC, vpyzhyanov commented on src/main/java/org/example/service/UserAuth.java
> +            inputOutput.output("Имя пользователя не может быть пустым");
Оказалось, что `UserAuth` это на самом деле `UserAuthService` задача которого выполнять регистрацию и аутентификацию. Значит опять тёмная сторона, этот сервис не должен общаться с пользователем, это не обработчик команды. 

- inputOutput надо вообще из этого класса убрать
- Сервис сам в состоянии проверить валидность входных данных (имя пользователя), хотя на самом деле это ответственность обработчика, а не сервиса и тем более userDao. Поэтому обработчик должен проверить корректность данных в самом начале, а потом все должны работать с непустыми правильно заполненными данными. Хотя от того, что сервис дополнительно проверит их на пустоту ничего страшного не случится.
- Ну и в этом случае нельзя глушить исключение

2024-12-13 19:43 UTC, vpyzhyanov commented on src/main/java/org/example/service/UserAuth.java
> +            inputOutput.output("Имя пользователя не может быть пустым");
аналогично

2024-12-13 19:43 UTC, vpyzhyanov commented on src/main/java/org/example/service/UserStatistics.java
> +            logger.error("Имя пользователя не может быть пустым", e);
нельзя просто так глушить исключение, надо отреагировать как-то

2024-12-13 19:43 UTC, vpyzhyanov commented on src/main/java/org/example/service/UserStatistics.java
>          return "Для получения информации о пользователе" +
судя по всему этот класс - обработчик одной из команд. Тогда ему совершенно легально можно использовать `inputOutput`. Но при условии, что вы даёте ему такое право и называете класс соответствующе

2024-12-13 19:43 UTC, vpyzhyanov commented on src/main/java/org/example/service/UserTraining.java
> +            inputOutput.output("Имя пользователя не может быть пустым");
слишком много мест с одинаковым кодом, это явно тёмная сторона ООП

2024-12-14 17:35 UTC, merged