Task 1
alivkas/speed-printing-master pull request #7
Opened 2024-11-03 07:32 UTC by alivkas

2024-11-03 11:34 UTC, YaEtoTui commented on pom.xml
> +    <dependencyManagement>
Сразу вопрос: проект модульный у вас? Есть ли в нем смысл?

2024-11-03 11:37 UTC, YaEtoTui commented on task-1/pom.xml
> +            <version>RELEASE</version>
А какой смысл тут указывать версию? Вы же берете зависиомсть из dependencyManagement

2024-11-03 11:40 UTC, YaEtoTui commented on task-1/src/main/java/org/example/processing/CommandHandler.java
> + * Класс для обработки команд пользователя.
А я погляжу вы интеллигент) писать точки))

2024-11-03 11:43 UTC, YaEtoTui commented on task-1/src/main/java/org/example/text/TextInteraction.java
> +import java.util.ArrayList;
не нужные импорты

2024-11-03 11:47 UTC, YaEtoTui commented on task-1/src/main/java/org/example/text/Typo.java
> +     * Конструктор Typo
не говорящее)) Я и так вижу что Typo

А вот который инициализирует такие-то поляи так. Это другое дело

2024-11-03 11:52 UTC, YaEtoTui commented on task-1/src/main/java/org/example/training/Result.java
> +     * @return
@return -> убрать

2024-11-03 12:00 UTC, YaEtoTui commented
![изображение](https://github.com/user-attachments/assets/24fd160e-319c-4578-bb77-81d7c7e1ba57)

Я посмотрел.
Во первых, почему после слов "Тренировка завершена", у меня почему-то 
нет было результатов, После нажатия Enter, появилось.

Во вторых, Показывает ошибки немножко не корректно, ошибся в слове в двух местах, показывает  и после.
И в конце откуда-то знаки, тоже не понял

2024-11-03 12:02 UTC, YaEtoTui commented on task-1/src/main/java/org/example/text/Typo.java
> +        int minLength = Math.min(splitCorrect.length, splitTypo.length);
Писал комментарий. Что-то в коде не досмотрели, так как у меня там на скрине я считаю не корректные моменты

2024-11-03 12:02 UTC, YaEtoTui commented on task-1/src/test/java/org/example/processing/ResponseProcessingTest.java
> +import org.example.processing.ResponseProcessing;
не нужный импорт

2024-11-03 12:03 UTC, YaEtoTui commented on task-1/src/test/java/org/example/text/TextInteractionTest.java
> +import java.util.List;
не нужный импорт

2024-11-03 12:04 UTC, YaEtoTui commented
> ![изображение](https://private-user-images.githubusercontent.com/102538132/382568882-24fd160e-319c-4578-bb77-81d7c7e1ba57.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzA2MzU1MjcsIm5iZiI6MTczMDYzNTIyNywicGF0aCI6Ii8xMDI1MzgxMzIvMzgyNTY4ODgyLTI0ZmQxNjBlLTMxOWMtNDU3OC1iYjc3LTgxZDdjN2UxYmE1Ny5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMTAzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTEwM1QxMjAwMjdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0xY2I5YzAwZWUwNWZmMTU3ZjdhZTJkMTAxODEyYWYyM2I1M2IxMzdlYmViN2Q2ZDgwOWE3MWM4NDZlNTA3NzIwJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.JWIy3BNFnlJMyRU3dlIsWeTD8RS1W6cjCY5FwyFlnS4)
> 
> Я посмотрел. Во первых, почему после слов "Тренировка завершена", у меня почему-то нет было результатов, После нажатия Enter, появилось.
> 
> Во вторых, Показывает ошибки немножко не корректно, ошибся в слове в двух местах, показывает и после. И в конце откуда-то знаки, тоже не понял

У вас же там идет подсчет, так что будут данные не верные

2024-11-03 12:05 UTC, YaEtoTui commented on task-1/src/test/java/org/example/training/TrainingSettingsTest.java
> +    void getTrainingTime() {
Это не getter а проверка

2024-11-03 12:05 UTC, YaEtoTui commented on task-1/src/test/java/org/example/text/TypoTest.java
> +    public void getTypoCountTest() {
это не getter

2024-11-03 12:06 UTC, YaEtoTui commented on task-1/src/test/java/org/example/training/TrainingSettingsTest.java
> +    void setTrainingTime() {
это не setter, не нужно так их называть

2024-11-03 12:06 UTC, YaEtoTui commented on task-1/src/test/java/org/example/web/ApiTest.java
> +import org.example.web.Api;
не нужный импорт

2024-11-03 12:08 UTC, YaEtoTui commented
В целом очень хорошо проработано) 

1 задание принято

2024-11-03 17:48 UTC, alivkas commented on pom.xml
> +    <dependencyManagement>
Проект не модульный. Убрали

2024-11-03 17:48 UTC, alivkas commented on task-1/pom.xml
> +            <version>RELEASE</version>
Исправили

2024-11-03 17:48 UTC, alivkas commented on task-1/src/main/java/org/example/text/TextInteraction.java
> +import java.util.ArrayList;
исправили

2024-11-03 17:48 UTC, alivkas commented on task-1/src/main/java/org/example/text/Typo.java
> +     * Конструктор Typo
исправили

2024-11-03 17:48 UTC, alivkas commented on task-1/src/main/java/org/example/training/Result.java
> +     * @return
исправили

2024-11-03 17:49 UTC, alivkas commented on task-1/src/main/java/org/example/text/Typo.java
> +        int minLength = Math.min(splitCorrect.length, splitTypo.length);
исправили

2024-11-03 17:49 UTC, alivkas commented on task-1/src/test/java/org/example/processing/ResponseProcessingTest.java
> +import org.example.processing.ResponseProcessing;
исправили

2024-11-03 17:49 UTC, alivkas commented on task-1/src/test/java/org/example/text/TextInteractionTest.java
> +import java.util.List;
исправили

2024-11-03 17:49 UTC, alivkas commented on task-1/src/test/java/org/example/training/TrainingSettingsTest.java
> +    void getTrainingTime() {
исправили

2024-11-03 17:49 UTC, alivkas commented on task-1/src/test/java/org/example/text/TypoTest.java
> +    public void getTypoCountTest() {
исправили

2024-11-03 17:49 UTC, alivkas commented on task-1/src/test/java/org/example/training/TrainingSettingsTest.java
> +    void setTrainingTime() {
исправили

2024-11-03 17:49 UTC, alivkas commented on task-1/src/test/java/org/example/web/ApiTest.java
> +import org.example.web.Api;
исправили

2024-11-07 17:55 UTC, vpyzhyanov commented
![image](https://github.com/user-attachments/assets/3221fbea-2584-4d83-aff7-c00a6545f072)

За это вы теряете 1 балл за Git

2024-11-07 18:04 UTC, vpyzhyanov commented
Дублируются одни и те же коммиты

![image](https://github.com/user-attachments/assets/d61b75a6-d84c-47c7-b20d-4eecaec08d71)

Надо было использовать merge

2024-11-07 18:06 UTC, vpyzhyanov commented
![image](https://github.com/user-attachments/assets/2f898826-aa50-4c98-bdad-3dd995870378)

Некомпилирующийся код приниматься не будет!

2024-11-07 18:17 UTC, YaEtoTui commented
> ![image](https://private-user-images.githubusercontent.com/71599019/384086006-2f898826-aa50-4c98-bdad-3dd995870378.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzEwMDMzODgsIm5iZiI6MTczMTAwMzA4OCwicGF0aCI6Ii83MTU5OTAxOS8zODQwODYwMDYtMmY4OTg4MjYtYWE1MC00Yzk4LWJkYWQtM2RkOTk1ODcwMzc4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMDclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTA3VDE4MTEyOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTVlNTg2NDllMjhmN2I2NDJjNTU0MTkyZTA2YjRkN2YyMzA0N2Q4N2U2YmZjOTQ1YjhhMGQ1NDAxZTYzYTUyZGImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.tnRIxAviwebMFz6RQAurh-7u2uGeA-V4NZ7Gqy29HxE)
> 
> Некомпилирующийся код приниматься не будет!

Вячеслав, при проверке он работал. Тут я уже увидел почему так.

Ребята, пожалуйста проверяйте что код работает при отправки изменений. Просто на глупом моменте.
А если вы бы уделяли МИНУТУ на это, проблем не возникло
alivkas, не подводите команду больше
![изображение](https://github.com/user-attachments/assets/55af4d4d-8f5d-426e-be83-51ba3135dea0)

2024-11-07 18:35 UTC, YaEtoTui commented on src/main/java/org/example/App.java
> +    /*
Вы тут хотели комментарий или JavaDoc? Повнимательнее

2024-11-07 18:38 UTC, alivkas commented on src/main/java/org/example/App.java
> +    /*
JavaDoc, виноват

2024-11-07 18:44 UTC, YaEtoTui commented on src/main/java/org/example/App.java
> +    /*
Вот так теперь понятно) Будьте повнимательнее

2024-11-07 18:45 UTC, YaEtoTui commented
Вячеслав будет дальше проверять. Код теперь компилируется, студенты поправили данный недочет

2024-11-07 20:11 UTC, vpyzhyanov requested changes
Поздравляю, вы теперь адепты тёмной стороны) Может на светлую лучше перейти?

2024-11-07 20:11 UTC, vpyzhyanov commented on pom.xml
> +            <artifactId>junit</artifactId>
вы уж определитесь либо вы используете JUnit 4 либо JUnit 5. Даже тесты у вас написаны на разных. Не все тесты могут запускаться из-за этого!

2024-11-07 20:11 UTC, vpyzhyanov commented on src/main/java/org/example/App.java
> +            System.out.print("Введите команду: ");
Хорошо бы перед этим написать какие команды есть

2024-11-07 20:11 UTC, vpyzhyanov commented on src/main/java/org/example/App.java
> +            commandHandler.handleCommand(input);
уже отсюда видно, что вы попали на тёмную сторону и перегрузили класс функционалом. Судя по тому, что метод ничего не возвращает можно сделать вывод, что этот метод ещё и выводит результат на консоль. Но об этом нигде не написано.

Всё таки операции чтения и вывода связаны, т.к. чтение из **консоли** и вывод на **консоль**. Поэтому неправильно их разделять. Получается ещё и коллективная безответственность тут

2024-11-07 20:11 UTC, vpyzhyanov commented on src/main/java/org/example/Main.java
> + *Запускает тренировочное приложение.
Добро пожаловать на тёмную сторону

![image](https://github.com/user-attachments/assets/c44ce19a-3de3-4ce2-bb4f-e3588bbf7035)

2024-11-07 20:11 UTC, vpyzhyanov commented on src/main/java/org/example/animation/Animation.java
> +            System.out.println(i + "...");
да, не легко вам придётся. Консоль явно расхолаживает тем, что вы в любой момент можете к ней обратиться. Но чтобы освоить ООП нужно познать мощь ограничений, даже для тех вещей, до которых вы можете дотянуться.

Чтобы вернуться на светлую сторону вам надо исправить ВСЕ такие места и ввод и вывод делать в одном единственном месте. Если говорить более общими словами, то надо отвязать ваше приложение от консоли, чтобы можно было его применить для другой платформы (не важно какой).

2024-11-07 20:11 UTC, vpyzhyanov commented on src/main/java/org/example/animation/Animation.java
> +        for (int i = 3; i >= 1; i--) {
"Магические числа". Смысл их не понятен. Нужно вынести в константы с понятным названием. Хотя бы тройку.

2024-11-07 20:11 UTC, vpyzhyanov commented on src/main/java/org/example/animation/Animation.java
> +                throw new RuntimeException(e);
нужно добавить человекочитаемое сообщение об ошибке

2024-11-07 20:11 UTC, vpyzhyanov commented on src/main/java/org/example/processing/CommandHandler.java
> +                setTrainingTime();
сеттер ничего не принимает, значит это не сеттер. Поменяйте название на более подходящее по смыслу. Не зря же вы JavaDoc писали

2024-11-07 20:11 UTC, vpyzhyanov commented on src/main/java/org/example/processing/CommandHandler.java
> +        String helpText = "/help - Все команды\n" +
почему бы не использовать современные средства и не сделать многострочную строку?

2024-11-07 20:11 UTC, vpyzhyanov commented on src/main/java/org/example/processing/CommandHandler.java
> +        System.out.println(helpText);
тут и везде не место работы с консолью

2024-11-07 20:11 UTC, vpyzhyanov commented on src/main/java/org/example/processing/CommandHandler.java
> +    private void setTrainingTime() {
> Запрос у пользователя времени тренировки и установки его.

Вот это неожиданный поворот! Никогда бы не догадался, что метод `setTrainingTime` будет что-то у пользователя запрашивать. Судя по называнию он должен взять уже готовое значение и сохранить его.

2024-11-07 20:11 UTC, vpyzhyanov commented on src/main/java/org/example/processing/CommandHandler.java
> +        Scanner scanner = new Scanner(System.in);
1. Не место работе с консолью в этом классе
2. Дублирование кода. Такие строки я уже видел

2024-11-07 20:11 UTC, vpyzhyanov commented on src/main/java/org/example/processing/CommandHandler.java
> +                throw new NumberFormatException();
обязательно должно быть человекочитаемое сообщение об ошибке. Иначе в случае проблемы вы не сможете разобраться с ошибкой

2024-11-07 20:11 UTC, vpyzhyanov commented on src/main/java/org/example/processing/CommandHandler.java
> +            trainingSettings.setTrainingTime(time); // Устанавливаем время в минутах
такой комментарий должен быть в JavaDoc, а не тут

2024-11-07 20:11 UTC, vpyzhyanov commented on src/main/java/org/example/processing/CommandHandler.java
> +        } catch (NumberFormatException numberFormatException) {
Смотрели Вовку в тридевятом царстве? Помните там были двое из ларца, одинаковых с лица? Вот у вас так же)))

Сам кинул исключение, сам и обработал. В чём смысл?

2024-11-07 20:11 UTC, vpyzhyanov commented on src/main/java/org/example/processing/CommandHandler.java
> +            System.out.println("Введите корректное число");
Представьте, что я буду писать на код ревью такие замечания: "Пишите код без ошибок", "Сделайте хорошо", "Переделайте",  .....

Всё это общие слова, которые мало что значат. Пишите конкретно. Какое число будет являться корректным?

2024-11-07 20:11 UTC, vpyzhyanov commented on src/main/java/org/example/processing/CommandHandler.java
> +        int durationMinutes = trainingSettings.getTrainingTime() * 60 * 1000;
"Магические числа". Их нужно вынести в константы с понятными именами. Меньше магии

2024-11-07 20:11 UTC, vpyzhyanov commented on src/main/java/org/example/processing/CommandHandler.java
> +        TrainingProcess trainingProcess = new TrainingProcess(this, trainingSession, trainingSettings);
Опа! Тёмная сторона обнаружена! Верный признак тёмной стороны - циклическая зависимость. TrainingProcess зависит от CommandHandler и наоборот, CommandHandler определяет TrainingProcess.

TrainingProcess не должен лезть в ответственность обработки команд

2024-11-07 20:11 UTC, vpyzhyanov commented on src/main/java/org/example/processing/ResponseProcessing.java
> +    public String cutText(String text) {
это называется `sanitize`

2024-11-07 20:11 UTC, vpyzhyanov commented on src/main/java/org/example/processing/ResponseProcessing.java
> +public class ResponseProcessing {
Добавьте Utils в конце имени. Так называются все классы, которые не работают с состоянием.

2024-11-07 20:11 UTC, vpyzhyanov commented on src/main/java/org/example/text/TextInteraction.java
> +public class TextInteraction {
Добавьте Utils в конце имени. Так называются все классы, которые не работают с состоянием.

2024-11-07 20:11 UTC, vpyzhyanov commented on src/main/java/org/example/text/TextInteraction.java
> +        return processedText.equals(input);
какой смысл в однострочном методе? Почему нельзя сразу equals вызвать?

2024-11-07 20:11 UTC, vpyzhyanov commented on src/main/java/org/example/text/TextInteraction.java
> +    public int wordsCountIncrease(String input) {
1. зачем тут слово `Increase`?
2. Любой метод должен содержать глагол, например `getWordsCount`

2024-11-07 20:11 UTC, vpyzhyanov commented on src/main/java/org/example/text/Typo.java
> +        this.typos = new LinkedHashMap<>();
Почему выбрали именно эту коллекцию?

2024-11-07 20:11 UTC, vpyzhyanov commented on src/main/java/org/example/text/Typo.java
> +                        markers.append(" ");
очень плохо, что не применили полученные знания на последней лекции. Какие тут знания нужно применить?

2024-11-07 20:11 UTC, vpyzhyanov commented on src/main/java/org/example/text/Typo.java
> +    public int getTypoCount() {
есть 2 метода с почти идентичным названием (`getTypoCounts`) и абсолютно разной логикой. Какая это тёмная сторона?

2024-11-07 20:11 UTC, vpyzhyanov commented on src/main/java/org/example/text/Typo.java
> +            typoCounts += getTypoCountInOneString(mark);
вы только представьте весь масштаб трагедии: метод называется "Получить", а он изменяет значение. Это как вы пришли бы на экзамен получить оценку, а вас на нём отчисляют

2024-11-07 20:11 UTC, vpyzhyanov commented on src/main/java/org/example/text/Typo.java
> +    public void clearTypoCount() {
Тёмная сторона коллективной безостветственности внутри одного класса. Есть 2 метода по очистке, но они почему-то разные. А вот вызываются в одном месте.

2024-11-07 20:11 UTC, vpyzhyanov commented on src/main/java/org/example/training/TrainingProcess.java
> +        typo.clearTypo();
если вы несколько раз обращаетесь к одному и тому же объекту подряд, то это значит вы на тёмной стороне. У тех кто на светлой стороне тут один метод вызывается.

2024-11-07 20:11 UTC, vpyzhyanov commented on src/main/java/org/example/training/Result.java
> +    public void printResult() {
давайте подумаем какая тут тёмная сторона?

2024-11-07 20:11 UTC, vpyzhyanov commented on src/main/java/org/example/training/Result.java
> +        getTyposWithMarks();
геттер ничего не возвращает, значит он не геттер

А тут следовало бы вернуть что-то

2024-11-07 20:11 UTC, vpyzhyanov commented on src/main/java/org/example/training/Result.java
> +            System.out.printf("%s\n%s%n", typoKey, marksValue);
1. Перенос на следующую строку - это `/n`, а не `%n`
2. Если у вас в конце перенос, то используйте println
3. Если у вас простой случай и его можно легко заменить конкатенацией, то сделайте это, ведь это намного эффективнее, чем парсить шаблон.

2024-11-07 20:11 UTC, vpyzhyanov commented on src/main/java/org/example/training/TrainingProcess.java
> +        this.scanner = new Scanner(System.in);
дублирование и перегруз по функционалу. Очень тёмная сторона

2024-11-07 20:11 UTC, vpyzhyanov commented on src/main/java/org/example/training/TrainingSession.java
> +    private final int lasting; // Длительность тренировки
не комментарий, а JavaDoc

2024-11-07 20:11 UTC, vpyzhyanov commented on src/main/java/org/example/training/TrainingSession.java
> +    private boolean session; // Статус активности сессии
не комментарий, а JavaDoc

2024-11-07 20:11 UTC, vpyzhyanov commented on src/main/java/org/example/training/TrainingSession.java
> +    private boolean session; // Статус активности сессии
boolean переменная всегда должна начинаться с логического **глагола**. `session` - это Сессия, к boolean не имеет никого отношения.

По вашему же комментарию можно легко написать нормальное имя: `isActive`

2024-11-07 20:11 UTC, vpyzhyanov commented on src/main/java/org/example/training/TrainingSession.java
> +        this.session = false; // Изначально не активна
если изначально назвать поле в соответствии с его смыслом, то такие коментарии будут не нужны. `isActive = false` - не требует пояснений

2024-11-07 20:11 UTC, vpyzhyanov commented on src/main/java/org/example/training/TrainingSession.java
> +                session = false;
насколько я вижу, многопоточку вы не изучали? Значит надо изучить прямо сейчас. В чём тут ошибка?

Подсказка: ошибка где-то в определении поля.

2024-11-07 20:11 UTC, vpyzhyanov commented on src/main/java/org/example/training/TrainingSession.java
> +                timer.cancel();
эмм.... и всё? Просто написали текст в консоль и тренировка завершилась? Не может такого быть. Наверное тут скрыта очень хитрая логика взятая с тёмной стороны.

И действительно. Оказывается всё завязано на методе isActive(). Ребята, это очень не очевидно. Получается мы тут сделали свою работу и поменяли "статус", а дальше ждём пока "он догадается на что она обиделась и позвонит и извинится" (отсылка к нелогичному поведению девушек), т.е. ждём пока кто-то извне на это среагирует. Не надо так. В программировании должна быть логика.

2024-11-07 20:11 UTC, vpyzhyanov commented on src/main/java/org/example/training/TrainingSession.java
> +            System.out.println("Тренировка остановлена");
то же самое

\+ никакой работы с консолью тут быть не должно

2024-11-07 20:11 UTC, vpyzhyanov commented on src/main/java/org/example/training/TrainingSession.java
> +    public boolean isActive() {
О, вот же есть нормальное название! Почему тогда поле называется по другому?

2024-11-07 20:11 UTC, vpyzhyanov commented on src/main/java/org/example/training/TrainingSettings.java
> +     * @param minutes время на тренировку
формат и единицы измерения пишутся в описании, а не в имени переменной

2024-11-07 20:11 UTC, vpyzhyanov commented on src/main/java/org/example/training/TrainingSettings.java
> +    private int trainingTime;
Добро пожаловать в коллективную безответственность

![image](https://github.com/user-attachments/assets/f7785aa1-bd47-43f6-a551-d19a90f44a6b)

2024-11-07 20:11 UTC, vpyzhyanov commented on src/main/java/org/example/training/TrainingSettings.java
> +     * @return время на тренеровку
русский язык надо повторить. В комментариях к коммитам тоже

2024-11-07 20:11 UTC, vpyzhyanov commented on src/main/java/org/example/web/Api.java
> +    public String getApi() {
Какого запроса? К какому api вы обращаетесь? Всё это надо отразить как в описании, так и в имени.

Возможно название класса тоже должно указывать на конкретный API

2024-11-07 20:11 UTC, vpyzhyanov commented on src/main/java/org/example/web/Api.java
> +            throw new RuntimeException(e);
человекочитаемое сообщение

2024-11-07 20:11 UTC, vpyzhyanov commented on src/test/java/org/example/processing/ResponseProcessingTest.java
> +        String text = new Api().getApi();
1. ох зря. Теперь я знаю как сломать вашу сборку. Как мне это удастся?
2. Зачем вам в тесте на ResponseProcessing обращаться к внешнему API?

2024-11-07 20:11 UTC, vpyzhyanov commented on src/test/java/org/example/training/TrainingProcessTest.java
> +    }
шикарный тест) Очень важный и необходимый)

Нет теста в общем

2024-11-07 20:11 UTC, vpyzhyanov commented on src/test/java/org/example/processing/CommandHandlerTest.java
> +        Assertions.assertTrue(outputStreamCaptor.toString().contains("Установите время тренировки с помощью команды /settings."));
тест ничего не тестирует. По крайней мере команду start точно

2024-11-07 20:11 UTC, vpyzhyanov commented on src/test/java/org/example/processing/CommandHandlerTest.java
> +        Assertions.assertTrue(outputStreamCaptor.toString().contains("Нет активной тренировки."));
тест ничего не тестирует. По крайней мере команду stop точно

2024-11-07 20:11 UTC, vpyzhyanov commented on src/test/java/org/example/processing/CommandHandlerTest.java
> +        System.setIn(in);
слишком рано это сделали. Очень не очевидно, что происходит

2024-11-07 20:11 UTC, vpyzhyanov commented on src/test/java/org/example/training/TrainingSessionTest.java
> +        trainingSession = new TrainingSession(1000);
опять магические числа

2024-11-07 20:11 UTC, vpyzhyanov commented on src/test/java/org/example/training/TrainingSessionTest.java
> +    public void testStart() throws InterruptedException {
название противоречит описанию

2024-11-07 20:11 UTC, vpyzhyanov commented on src/test/java/org/example/training/TrainingSessionTest.java
> +    public void testStop() {
название противоречит описанию

2024-11-07 20:11 UTC, vpyzhyanov commented on src/test/java/org/example/training/TrainingSessionTest.java
> +        Assertions.assertFalse(trainingSession.isActive());
на следующей лекции как раз изучим почему так делать не надо

2024-11-07 20:11 UTC, vpyzhyanov commented on src/test/java/org/example/web/ApiTest.java
> +    public void getApiTest() {
зря, теперь я могу сломать вашу сборку и тесты. Как мне это удастся?

2024-11-07 20:16 UTC, vpyzhyanov commented
Сразу не заметил. Ещё -1 балл за прямые коммиты в ветку task-1

![image](https://github.com/user-attachments/assets/5bb901fd-8e3a-4664-8976-f8dea93f0cf5)

2024-11-14 08:10 UTC, alivkas commented on pom.xml
> +            <artifactId>junit</artifactId>
исправили

2024-11-14 08:10 UTC, alivkas commented on src/main/java/org/example/App.java
> +            System.out.print("Введите команду: ");
исправили

2024-11-14 08:10 UTC, alivkas commented on src/main/java/org/example/App.java
> +            commandHandler.handleCommand(input);
исправили

2024-11-14 08:10 UTC, alivkas commented on src/main/java/org/example/Main.java
> + *Запускает тренировочное приложение.
исправили

2024-11-14 08:11 UTC, alivkas commented on src/main/java/org/example/animation/Animation.java
> +            System.out.println(i + "...");
исправили

2024-11-14 08:11 UTC, alivkas commented on src/main/java/org/example/animation/Animation.java
> +        for (int i = 3; i >= 1; i--) {
исправили

2024-11-14 08:11 UTC, alivkas commented on src/main/java/org/example/animation/Animation.java
> +                throw new RuntimeException(e);
исправили

2024-11-14 08:11 UTC, alivkas commented on src/main/java/org/example/processing/CommandHandler.java
> +                setTrainingTime();
исправили

2024-11-14 08:11 UTC, alivkas commented on src/main/java/org/example/processing/CommandHandler.java
> +        System.out.println(helpText);
исправили

2024-11-14 08:11 UTC, alivkas commented on src/main/java/org/example/processing/CommandHandler.java
> +    private void setTrainingTime() {
исправили

2024-11-14 08:11 UTC, alivkas commented on src/main/java/org/example/processing/CommandHandler.java
> +        Scanner scanner = new Scanner(System.in);
исправили

2024-11-14 08:11 UTC, alivkas commented on src/main/java/org/example/processing/CommandHandler.java
> +                throw new NumberFormatException();
исправили

2024-11-14 08:11 UTC, alivkas commented on src/main/java/org/example/processing/CommandHandler.java
> +            trainingSettings.setTrainingTime(time); // Устанавливаем время в минутах
исправили

2024-11-14 08:12 UTC, alivkas commented on src/main/java/org/example/processing/CommandHandler.java
> +        } catch (NumberFormatException numberFormatException) {
исправили

2024-11-14 08:12 UTC, alivkas commented on src/main/java/org/example/processing/CommandHandler.java
> +            System.out.println("Введите корректное число");
исправили

2024-11-14 08:12 UTC, alivkas commented on src/main/java/org/example/processing/CommandHandler.java
> +        int durationMinutes = trainingSettings.getTrainingTime() * 60 * 1000;
исправили

2024-11-14 08:12 UTC, alivkas commented on src/main/java/org/example/processing/CommandHandler.java
> +        TrainingProcess trainingProcess = new TrainingProcess(this, trainingSession, trainingSettings);
исправили

2024-11-14 08:12 UTC, alivkas commented on src/main/java/org/example/processing/ResponseProcessing.java
> +    public String cutText(String text) {
исправили

2024-11-14 08:12 UTC, alivkas commented on src/main/java/org/example/processing/ResponseProcessing.java
> +public class ResponseProcessing {
исправили

2024-11-14 08:12 UTC, alivkas commented on src/main/java/org/example/text/TextInteraction.java
> +public class TextInteraction {
исправили

2024-11-14 08:12 UTC, alivkas commented on src/main/java/org/example/text/TextInteraction.java
> +        return processedText.equals(input);
исправили

2024-11-14 08:13 UTC, alivkas commented on src/main/java/org/example/text/TextInteraction.java
> +    public int wordsCountIncrease(String input) {
исправили

2024-11-14 08:20 UTC, alivkas commented on src/main/java/org/example/text/Typo.java
> +        this.typos = new LinkedHashMap<>();
LinkedHashMap нужен был для порядка в коллекции и быстрой итерации по ней

2024-11-14 08:20 UTC, alivkas commented on src/main/java/org/example/text/Typo.java
> +                        markers.append(" ");
исправили

2024-11-14 08:24 UTC, alivkas commented on src/main/java/org/example/text/Typo.java
> +            typoCounts += getTypoCountInOneString(mark);
исправили

2024-11-14 08:25 UTC, alivkas commented on src/main/java/org/example/text/Typo.java
> +    public int getTypoCount() {
коллективная безответственность. исправили

2024-11-14 08:25 UTC, alivkas commented on src/main/java/org/example/text/Typo.java
> +    public void clearTypoCount() {
исправили

2024-11-14 08:26 UTC, alivkas commented on src/main/java/org/example/training/TrainingProcess.java
> +        typo.clearTypo();
исправили

2024-11-14 08:27 UTC, alivkas commented on src/main/java/org/example/training/Result.java
> +    public void printResult() {
коллективная безответственность. Result не должен знать, что существует консоль. Исправили

2024-11-14 08:27 UTC, alivkas commented on src/main/java/org/example/training/Result.java
> +        getTyposWithMarks();
исправили

2024-11-14 08:27 UTC, alivkas commented on src/main/java/org/example/training/Result.java
> +            System.out.printf("%s\n%s%n", typoKey, marksValue);
исправили

2024-11-14 08:27 UTC, alivkas commented on src/main/java/org/example/training/TrainingProcess.java
> +        this.scanner = new Scanner(System.in);
исправили

2024-11-14 08:27 UTC, alivkas commented on src/main/java/org/example/training/TrainingSession.java
> +    private final int lasting; // Длительность тренировки
исправили

2024-11-14 08:27 UTC, alivkas commented on src/main/java/org/example/training/TrainingSession.java
> +    private boolean session; // Статус активности сессии
исправили

2024-11-14 08:27 UTC, alivkas commented on src/main/java/org/example/training/TrainingSession.java
> +    private boolean session; // Статус активности сессии
исправили

2024-11-14 08:27 UTC, alivkas commented on src/main/java/org/example/training/TrainingSession.java
> +        this.session = false; // Изначально не активна
исправили

2024-11-14 08:27 UTC, alivkas commented on src/main/java/org/example/training/TrainingSession.java
> +                session = false;
исправили

2024-11-14 08:28 UTC, alivkas commented on src/main/java/org/example/training/TrainingSession.java
> +                timer.cancel();
исправили

2024-11-14 08:28 UTC, alivkas commented on src/main/java/org/example/training/TrainingSession.java
> +            System.out.println("Тренировка остановлена");
исправили

2024-11-14 08:28 UTC, alivkas commented on src/main/java/org/example/training/TrainingSettings.java
> +     * @param minutes время на тренировку
исправили

2024-11-14 08:28 UTC, alivkas commented on src/main/java/org/example/training/TrainingSettings.java
> +    private int trainingTime;
исправили

2024-11-14 08:28 UTC, alivkas commented on src/main/java/org/example/web/Api.java
> +    public String getApi() {
исправили

2024-11-14 08:28 UTC, alivkas commented on src/main/java/org/example/web/Api.java
> +            throw new RuntimeException(e);
исправили

2024-11-14 08:28 UTC, alivkas commented on src/test/java/org/example/processing/ResponseProcessingTest.java
> +        String text = new Api().getApi();
исправили

2024-11-14 08:30 UTC, alivkas commented on src/test/java/org/example/training/TrainingProcessTest.java
> +    }
исправили

2024-11-14 08:30 UTC, alivkas commented on src/test/java/org/example/processing/CommandHandlerTest.java
> +        Assertions.assertTrue(outputStreamCaptor.toString().contains("Установите время тренировки с помощью команды /settings."));
исправили

2024-11-14 08:30 UTC, alivkas commented on src/test/java/org/example/processing/CommandHandlerTest.java
> +        Assertions.assertTrue(outputStreamCaptor.toString().contains("Нет активной тренировки."));
исправили

2024-11-14 08:30 UTC, alivkas commented on src/test/java/org/example/processing/CommandHandlerTest.java
> +        System.setIn(in);
исправили

2024-11-14 08:30 UTC, alivkas commented on src/test/java/org/example/training/TrainingSessionTest.java
> +        trainingSession = new TrainingSession(1000);
исправили

2024-11-14 08:30 UTC, alivkas commented on src/test/java/org/example/training/TrainingSessionTest.java
> +    public void testStart() throws InterruptedException {
исправили

2024-11-14 08:30 UTC, alivkas commented on src/test/java/org/example/training/TrainingSessionTest.java
> +    public void testStop() {
исправили

2024-11-14 08:31 UTC, alivkas commented on src/test/java/org/example/training/TrainingSessionTest.java
> +        Assertions.assertFalse(trainingSession.isActive());
исправили

2024-11-14 08:32 UTC, alivkas commented on src/test/java/org/example/web/ApiTest.java
> +    public void getApiTest() {
исправили. Насколько я понял, при выключении интернета программа выкидывает ошибку, из-за этого без сети сбилдить проект не получится

2024-11-20 20:30 UTC, vpyzhyanov commented on pom.xml
> +                    <argLine>-javaagent:${settings.localRepository}/org/mockito/mockito-core/${mockito-core.version}/mockito-core-${mockito-core.version}.jar -XX:+EnableDynamicAgentLoading</argLine>
что в этой строчке делает mockito?

2024-11-20 20:30 UTC, vpyzhyanov commented on src/main/java/org/example/Main.java
> +            if (command.equals("/start")) {
Почему-то с тёмной стороны коллективной безответственности вырваться не удалось( Зачем тогда нужен класс CommandHandler, если вы и без него команды обрабатываете?

2024-11-20 20:30 UTC, vpyzhyanov commented on src/main/java/org/example/Console.java
> +     * Выводить строку
Опять обидели полиморфизм и выбросили его на свалку. Без принципов ООП построить ООП приложение вообще никак не получится. Полностью обесценили интерфейс, который сами создали. JavaDoc в нём уже описан и переписывать его ни в коем случае нельзя

2024-11-20 20:30 UTC, vpyzhyanov commented on src/main/java/org/example/Console.java
> +     * Читает строку из входного потока.
аналогично

2024-11-20 20:30 UTC, vpyzhyanov commented on src/main/java/org/example/animation/Animation.java
> +        for (int i = 3; i >= 1; i--) {
я просил вынести в константу. Поле появилось, но константа в каноническом смысле - нет.

2024-11-20 20:30 UTC, vpyzhyanov commented on src/main/java/org/example/animation/Animation.java
> +    private final int COUNT = 3;
static

2024-11-20 20:30 UTC, vpyzhyanov commented on src/main/java/org/example/utils/log/LogsWriterUtils.java
> +    private final String FILE_NAME = "trace.log";
static

2024-11-20 20:30 UTC, vpyzhyanov commented on src/main/java/org/example/training/TrainingSession.java
> +    private final int SECINDS_IN_MINUTE = 60;
вы забыли слово static, или вы настолько его испугались? А вы ведь понимаете, что на каждый экземпляр теперь будет выделяться память на одно и то же значение?

2024-11-20 20:30 UTC, vpyzhyanov commented on src/main/java/org/example/text/Typo.java
> +                        markers.append(" ");
Нет ответа на вопрос!!! Вообще-то я вопросы задаю не просто так, а для того, чтобы вы чему-то научились, либо чтобы увидеть ваши знания и понимание.

Что исправили?

2024-11-20 20:30 UTC, vpyzhyanov commented on src/main/java/org/example/text/Typo.java
> +    private final int OPERATIONS = 2;
static

2024-11-20 20:30 UTC, vpyzhyanov commented on src/main/java/org/example/training/TrainingSession.java
> +                session = false;
Нет ответа на вопрос!

2024-11-20 20:30 UTC, vpyzhyanov commented on src/main/java/org/example/training/TrainingSettings.java
> +    private int trainingTime;
Как раз эта тёмная сторона не позволила вам сдать задачу сразу

2024-11-20 20:30 UTC, vpyzhyanov commented on src/main/java/org/example/web/FishTextApi.java
> +    private String getTextFromFishTextApi() {
название класса дублировать в имени не нужно, пишите только суть. Например `getGeneratedText` или `generateText`

2024-11-20 20:30 UTC, vpyzhyanov commented on src/main/java/org/example/web/Api.java
> +            throw new RuntimeException(e);
Исправлено неправильно. Вместо того. чтобы исправить конкретное замечание, вы совершили другую, куда более серьёзную ошибку. Теперь вы почему-то выдаёте исключительную ситуацию (которой происходить не должно) за нормальный текст. О том, что что-то пошло не так, никто даже не узнает.

2024-11-20 20:30 UTC, vpyzhyanov commented on src/main/java/org/example/web/FishTextApi.java
> +                return "Ошибка получения данных из API";
Вместо того. чтобы исправить конкретное замечание, вы совершили другую, куда более серьёзную ошибку. Теперь вы почему-то выдаёте исключительную ситуацию (которой происходить не должно) за нормальный текст. О том, что что-то пошло не так, никто даже не узнает.

2024-11-20 20:30 UTC, vpyzhyanov commented on src/main/java/org/example/web/FishTextApi.java
> +            return "Нет подключения к интернету";
аналогично

2024-11-20 20:30 UTC, vpyzhyanov commented on src/main/java/org/example/web/FishTextApi.java
> +            return "Нет данных из API";
аналогично

2024-11-20 20:30 UTC, vpyzhyanov commented on src/test/java/org/example/processing/ResponseProcessingTest.java
> +        String text = new Api().getApi();
правильно

2024-11-20 20:30 UTC, vpyzhyanov commented on src/test/java/org/example/training/TrainingSessionTest.java
> +    public void testStart() throws InterruptedException {
В каком месте исправили? Вообще ничего не изменилось!

2024-11-20 20:50 UTC, vpyzhyanov requested changes
Очень жаль. Выбраться из тёмной стороны не получилось, даже после моих подсказок((( Даже в процессе исправления замечаний были допущены критичные ошибки: потеря полиморфизма, повторение использования тёмной стороны, ошибки в тестах.

Не на все вопросы я увидел ответ. Не все замечания исправлены. Самое страшное, что в них написано, что вы их якобы исправили. Виду в этом сопротивление обучению? ЗАчем вы это делаете?

Как исправите замечания, можете мёрджить. Задача принята, но к сожалению не с самой высокой оценкой. Оценка за ООП 2 балла.

2024-11-20 20:50 UTC, vpyzhyanov commented on src/test/java/org/example/TestInputOutput.java
> +    private String input;
не используется

2024-11-20 20:50 UTC, vpyzhyanov commented on src/test/java/org/example/TestInputOutput.java
> +    private String latestOutput;
что толку от того, что вы её сохранили? Вы не сможете к ней обратиться

2024-11-20 20:50 UTC, vpyzhyanov commented on src/test/java/org/example/training/TrainingSessionTest.java
>  public class TrainingSessionTest {
Подозреваю, что тест ничего не тестирует

2024-11-20 20:50 UTC, vpyzhyanov commented on src/test/java/org/example/training/TrainingSessionTest.java
> +    private TestInputOutput testInputOutput;
это поле вообще нигде не используется. Что толку было его создавать, если потом никаких обращений к нему нет. Никаких проверок тоже нет. "чтобы было"?

2024-11-20 20:50 UTC, vpyzhyanov commented on src/test/java/org/example/training/TrainingSessionTest.java
> +        trainingSettings = new TrainingSettings();
Настройки не меняются в тестах. Не надо их каждый раз создавать заново

2024-11-20 20:50 UTC, vpyzhyanov commented on src/test/java/org/example/training/TrainingSessionTest.java
>          Assertions.assertTrue(trainingSession.isActive());
вообще-то этот метод делает далеко не только установку этого флажка. Тест явно не полный

2024-11-20 20:50 UTC, vpyzhyanov commented on src/test/java/org/example/training/TrainingSessionTest.java
> +    public void testStop() {
В каком месте? Всё так же название и описание из разных миров

2024-11-20 20:50 UTC, vpyzhyanov commented on src/test/java/org/example/training/TrainingSessionTest.java
>          Assertions.assertFalse(trainingSession.isActive());
разве это признак остановки тренировки? Не только ведь

2024-11-20 20:50 UTC, vpyzhyanov commented on src/test/java/org/example/training/TrainingSessionTest.java
> +        Assertions.assertFalse(trainingSession.isActive());
в каком месте исправили? Что исправили? Ничего не исправлено!!!

2024-11-20 20:50 UTC, vpyzhyanov commented on src/test/java/org/example/training/TrainingSessionTest.java
> +        Thread.sleep(1010);
это зачем? В описании про это ни слова. Смысл этой строчки непонятен

2024-11-20 20:50 UTC, vpyzhyanov commented on src/test/java/org/example/training/TrainingSessionTest.java
>  public class TrainingSessionTest {
И действительно, Название говорит о том, что тест проверяет TrainingSession, но это не так. Он проверяет только один флажочек `isActive`. Но этот класс одним флажочком не ограничивается. Его работа куда сложнее и интереснее, но это никто не тестирует, почему-то.

Зато описание говорит правду))))) Но от этого не легче(

2024-11-20 20:50 UTC, vpyzhyanov commented on src/test/java/org/example/utils/log/LogsWriterUtilsTest.java
> +        reader.close();
пожалуйста, прямо сейчас почитайте как правильно работать с потоками ввода-вывода. Это очень грубая ошибка

2024-11-20 20:50 UTC, vpyzhyanov commented on src/test/java/org/example/utils/log/LogsWriterUtilsTest.java
> +        Assertions.assertTrue(fileContent.toString().contains("Произошло исключение"));
Всегда используйте equals, а не contains

2024-11-20 20:50 UTC, vpyzhyanov commented on src/test/java/org/example/utils/log/LogsWriterUtilsTest.java
> +        Assertions.assertTrue(fileContent.toString().contains("Это тестовое исключение"));
Всегда используйте equals, а не contains

2024-11-20 20:54 UTC, vpyzhyanov commented on src/test/java/org/example/training/TrainingSessionTest.java
> +    public void testStart() throws InterruptedException {
уточню, проблема в названии. Под описание подходит название `testSessionIsActiveWhileSettedTime`. Ну или что-то в этом духе

2024-11-20 20:55 UTC, vpyzhyanov commented on src/test/java/org/example/training/TrainingSessionTest.java
> +    public void testStop() {
уточню, проблема в названии. Под описание подходит название `testSessionIsNotActiveAfterStop`. Ну или что-то в этом духе

2024-11-20 20:58 UTC, vpyzhyanov commented
Вы запускали сборку? Она порождает циклический запуск этой же сборки в несколько отдельных потоков. Так быть точно не должно.

2024-11-22 15:16 UTC, SolevarLive commented on src/main/java/org/example/training/TrainingSession.java
> +                session = false;
В прошлой реализации переменная была не потокобезопасной

2024-11-22 15:32 UTC, SolevarLive commented on src/test/java/org/example/training/TrainingSessionTest.java
> +    public void testStart() throws InterruptedException {
Исправлено название теста

2024-11-22 15:34 UTC, SolevarLive commented on src/test/java/org/example/training/TrainingSessionTest.java
> +    public void testStop() {
Исправлено название теста

2024-11-22 16:06 UTC, SolevarLive commented on src/test/java/org/example/training/TrainingSessionTest.java
> +    private TestInputOutput testInputOutput;
Добавлена проверки на вывод сообщения

2024-11-22 16:45 UTC, SolevarLive commented on src/test/java/org/example/training/TrainingSessionTest.java
>          Assertions.assertFalse(trainingSession.isActive());
Нет, не полный признак. 
Для полноты теста добавлена проверка  на вывод "Тренировка завершена после команды "стоп""

2024-11-22 16:51 UTC, SolevarLive commented on src/test/java/org/example/training/TrainingSessionTest.java
> +        Thread.sleep(1010);
Видимо осталось от старой реализации, после рефакторинга забыл убрать

2024-11-22 19:25 UTC, SolevarLive commented on src/test/java/org/example/training/TrainingSessionTest.java
>  public class TrainingSessionTest {
Дополнил тестом, и расширил уже имеющийся тест

2024-11-23 17:28 UTC, vpyzhyanov commented on src/main/java/org/example/training/Result.java
> +    public void printResult() {
решил пересмотреть оценку за ООП и добавить 1 балл за попытку сделать настоящую инкапсуляцию. Тут вы молодцы!

2024-11-23 17:29 UTC, vpyzhyanov commented
Повысил оценку за ООП до 3 баллов

2024-11-30 13:32 UTC, merged